# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- refs/tags/v*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.x'
    installationPath: 'C:\Program Files\dotnet'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    filePath: '.\pack-basilisk.ps1'
    arguments: '-TargetsDir $(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: 'Push to NuGet Feed'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'bba043b4-7881-4113-893f-afa6407d0589/14249dea-5581-4b50-86bf-4d1642f136b4'
    publishPackageMetadata: false
